name: Codebase lint
on: [push, pull_request]

jobs:
  lint-client:
    name: Client side lint and quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - name: Install dependencies
        run: yarn install --no-lockfile --prefer-offline

      - name: Format check via Prettier
        run: yarn prettier --check .
        continue-on-error: true

      - name: Format check via ESLint
        run: yarn eslint -c eslintrc.format.cjs .

      - name: Code quality check via ESLint
        run: yarn eslint .

  # Python stuff
  lint-server:
    name: Python lint and type check
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install dependencies
        run: |
          pip install pycodestyle
          pip install -r requirements.txt

      - name: pycodestyle (pep8) linting
        run: pycodestyle .
        continue-on-error: true

      - name: Type checking
        run: 'mypy $(find . -type f -name "*.py" ! -path "./venv/**")'
